<div class="error">
    <h1>ERROR URL</h1>

    <div class="content-404">
        // TODO: hardcoding
        <img src="http://127.0.0.1/local.magento/skin/frontend/open/default/images/error-img.png" class="img-responsive" alt="" />
        <h1><b>OPPS!</b> We Couldn’t Find this Page</h1>
        <p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
        <h2><a href="http://127.0.0.1/local.magento/index.php">Bring me back Home</a></h2>
    </div>
</div>