<div class="container text-center">
    <div class="logo-404">
        <a href="<?= $this->getUrl('index.php') ?>">
            <img src="<?= $this->getSkinUrl('images/media/logo.png')?>" alt="" />
        </a>
    </div>
    <div class="content-404">
        <img src="<?= $this->getSkinUrl('images/404.png')?>" class="img-responsive" alt="" />
        <h1><b>OPPS!</b> We Could not Find this Page</h1>
        <p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
        <h2><a href="<?= $this->getUrl() ?>">Bring me back Home</a></h2>
    </div>
</div>